excerpt_separator: ""
highlighter: pygments
markdown: kramdown
url: http://code.koffisani.ga
highlighter: rouge
title: "Koffi Sani on Code"
tagline: "Un log de mes activités de conception de logiciels"
description: "Permettez que je parle ici de ma vie de concepteur de logiciels"
paginate: 5
timezone: Africa/Lomé
encoding: utf-8

url: "https://code.koffisani.ga"
disqus_identfier: koffisani
twitter_username: koffisani
github_username:  koffisani
linkedin_username: koffisani
fb_username: koffisani
adresse_web: "https://www.koffisani.ga"

#Text extension activation
services:
  twig.extension.text:
    class: Twig_Extensions_Extension_Text
    tags:
      - { name: twig.extension }


#HTTPS enforce
#enforce_ssl : koffisani.github.io

#github: [metadata]
#  kramdown:
#    input: GFM
#    hard_wrap: false

gems:
  - jekyll-seo-tag
  - jekyll-coffeescript
  - jekyll-paginate
  - jekyll-avatar
  - jekyl-gist
  - jekyll-mentions

twitter:
  username: koffisani

facebook:
  app_id: 1684328031825738
  publisher: 1684328031825738

logo: /img/sani-koffi.jpg
social:
  name: Koffi Sani
  links:
    - https://facebook.com/koffisani
    - https://twitter.com/koffisani
    - https://linkedin.com/in/koffisani
    - https://plus.google.com/+koffisani
  images: /img/koffi.png
google_site_verification: googleaf6a5e28ab29fc8d.html
