excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://koffisani.github.io
title: Koffi Sani on GitHub
tagline: A log of my everyday coding life
description: Let me land my everyday coding life here
paginate: 5

#Text extension activation
services:
  twig.extension.text:
    class: Twig_Extensions_Extension_Text
    tags:
      - { name: twig.extension }
      
