excerpt_separator: ""
pygments: true
markdown: kramdown
url: https://koffisani.github.io
highlighter: rouge
title: Koffi Sani on GitHub
tagline: A log of my everyday coding life
description: Let me land my everyday coding life here
paginate: 5

url: "https://koffisani.github.io"
twitter_username: koffisani
github_username:  koffisani
linkedin_username: koffisani
fb_username: koffisani

#Text extension activation
services:
  twig.extension.text:
    class: Twig_Extensions_Extension_Text
    tags:
      - { name: twig.extension }
      
      
#HTTPS enforce
enforce_ssl : koffisani.github.io

gems:
  - jekyll-seo-tag
      
twitter:
  username: koffisani
  
facebook:
  app_id: 1684328031825738
  publisher: 1684328031825738
  
logo: /img/koffi.jpg
social: 
  name: Koffi Sani
  links: 
    https://facebook.com/koffisani
    https://twitter.com/koffisani
    https://linkedin.com/in/koffisani
    https://plus.google.com/+koffisani
  images: /img/koffi.png
google_site_verification: googleaf6a5e28ab29fc8d.html
